name: buildkite-CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Trigger Buildkite Pipeline
      uses: buildkite/trigger-pipeline-action@v1.2.0
      env:
        PIPELINE: "cloud-hypervisor/vm-memory-ci"
        COMMIT: "HEAD"
        BRANCH: "master"
        MESSAGE: "GitHub cloud-hypervisor/rust-vmm action"
        BUILDKITE_API_ACCESS_TOKEN: ${{ secrets.BUILDKITE_API_ACCESS_TOKEN }}

